### ISSUE TITLE
Twitter API keys are public

### ISSUE THREAD

**Issue by Devansh3712** [arnav10goel/Twitter_Bot#1]
Hi, it is a common practice not to upload the API keys publicly, as someone else might use them to impersonate you. Add `twitterKeys.yaml` to the `.gitignore` file and it will not commit it to the repository, and yours keys will be safe. Have a great day!

**Comment by arnav10goel** [comment]
Hi, thanks for pointing this out. Did not know about this. Could you please check if it is fine now?

**Comment by Devansh3712** [comment]
No the contents stay in `twitterKeys.yaml`, just put a line `twitterKeys.yaml` in `.gitignore` not the contents of it. That way when you're commiting other files it will ignore the yaml file and thus your keys won't be posted.

**Comment by arnav10goel** [comment]
Oh okay, I added the twitterKeys.yaml line to .gitignore. However upon recommitting it, twitterKeys.yaml is still being committed. Could you tell me where am I going wrong? Should I remove twitterKeys.yaml from the local repo on my machine before committing?
